[config]
schemaVersion = "0.0.1"

[package]
namespace = "MyTeamName"
name = "MyCoolMod"
versionNumber = "0.0.1"
description = "Insert a description about your mod here that's under 256 characters."
websiteUrl = "urlToMyGitOrSomething"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Ostranauts = "5.4.2303"
bitMods-LaunchControl = "1.0.3"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./dist/thunderstore"

[[build.copy]]
source = "./artifact"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["ostranauts"]

[publish.categories]
ostranauts = ["mods"]


